Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/opt/alt/python310/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rest_framework'
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
Traceback (most recent call last):
  File "/home/hakabvzf/ecommerce.hakateq.com/passenger_wsgi.py", line 8, in <module>
    wsgi = imp.load_source('wsgi', 'project/wsgi.py')
  File "/opt/alt/python310/lib64/python3.10/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hakabvzf/virtualenv/ecommerce.hakateq.com/3.10/lib/python3.10/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
